### ISSUE TITLE
Plugin is not compatible - Cacti Version 1.0.0

### ISSUE THREAD

**Issue by stuieordie** [n00badmin/mirage#2]
I'm testing out a new install of Cacti 1.0.0 and found that mirage is showing as not compatible. I downloaded mirage-1.2.0.tgz from docs.cacti.net.

Screenshot in Cacti: http://imgur.com/a/lCFVW

**Comment by l00py** [comment]
Hi there,

We have updated Mirage to 1.3.0 to support Cacti 1.0.x. 
It is also backward compatible.

Let us know if you run into any issues.

Thank you.

**Cacti 1.0.1**
![image](https://cloud.githubusercontent.com/assets/16730071/22796742/8e90a9b4-eec9-11e6-8d77-7498d351b4f7.png)
![image](https://cloud.githubusercontent.com/assets/16730071/22796750/94aef170-eec9-11e6-8362-30729c3d40f0.png)
![image](https://cloud.githubusercontent.com/assets/16730071/22796762/9bcf9176-eec9-11e6-8bb1-a52e5a727322.png)

**Cacti 0.8.8h**
![image](https://cloud.githubusercontent.com/assets/16730071/22796783/b88406d0-eec9-11e6-8c55-06db6b3f8c02.png)

**Comment by l00py** [comment]
Hi there,

We have updated Mirage to 1.3.0 to support Cacti 1.0.x. 
It is also backward compatible.

Let us know if you run into any issues.

Thank you.

**Cacti 1.0.1**
![image](https://cloud.githubusercontent.com/assets/16730071/22796742/8e90a9b4-eec9-11e6-8d77-7498d351b4f7.png)
![image](https://cloud.githubusercontent.com/assets/16730071/22796750/94aef170-eec9-11e6-8362-30729c3d40f0.png)
![image](https://cloud.githubusercontent.com/assets/16730071/22796762/9bcf9176-eec9-11e6-8bb1-a52e5a727322.png)

**Cacti 0.8.8h**
![image](https://cloud.githubusercontent.com/assets/16730071/22796783/b88406d0-eec9-11e6-8c55-06db6b3f8c02.png)
