### ISSUE TITLE
Cacti - Quick Chart - Incorrect Wording

### ISSUE THREAD

**Issue by netniV** [n00badmin/mirage#6]
The Quick Chart states that it "Could not create search." beneath every drop down box apart from the first and last.  But, in reality, it is waiting for a selection, usually of the previous box.  

I thought something was wrong with the system and only happened to take a chance by clicking in the first box to find the next populated and the message disappeared.

**Comment by n00badmin** [comment]
I will install the app and have a look. Might be more of a core Splunk thing. 

App is way overdue for some clean up anyways. Will be looking at that this month.

**Comment by netniV** [comment]
Cool. Can't wait.
