### ISSUE TITLE
Cacti - Quick Chart - Object name becomes index number

### ISSUE THREAD

**Issue by netniV** [n00badmin/mirage#7]
If you select an item in each of the combo boxes, then change the hostnames combo box to a different host that also has the same KPI, the object combo box shows the ID of the previous selection.

**eg, if you have the following:**
```
Cacti Host: test1
Hostnames.: test-server1
KPI.......: hdd_used
Object....: test-server-1 - Used Space - Physical Memory
```

**Then change it to test-server2, you will see**
```
Cacti Host: test1
Hostnames.: test-server1
KPI.......: hdd_used
Object....: 251
```

**Changing back reverts to showing the name as at the start.  This is wrong for two reasons, One, it is the index number of the object on the previous host I suspect. Two, it should be cleared for new selection**

**Comment by n00badmin** [comment]
Hey netniV, will have a look at this shortly. 

I will be sure to create another repo for the Splunk app. This one is for the actual Cacti plugin.
