### ISSUE TITLE
Renaming the unzipped directory is a pain

### ISSUE THREAD

**Issue by patrickscottbest** [n00badmin/mirage#8]
# Carve a Release
You guys need to carve a "Release" so people don't have to rename the unzipped folder "mirage-master" to "mirage".  

Releases -> create -> call the tag "mirage" and select the branch you want.... presumably master.  This way when ppl download the zip, it will be called mirage.zip and not mirage-master.zip.  select pre-release if you want.  

# Make it the most attractive download option

Grab the URL of the download and throw it in your readme.md file at the top so people can click the right one. 

# Look at my repo as an example.

Follow me and check out hammerOID for an example of what i mean.

**Comment by n00badmin** [comment]
thanks for the feedback pat! will look at this asap!

**Comment by patrickscottbest** [comment]
Burying this carcass. You guys do good work, this isn't urgent.
